language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - node_modules/.bin/gulp ts
  - node_modules/.bin/gulp test:unit --Firefox
  - node_modules/.bin/gulp test:e2e --firefox

addons:
  code_climate:
    repo_token: 27fefdd920bc01066288a69e24469db3c9b33ef397a99f819622bc96aea604b7

after_script:
  - cat coverage/report-lcov/lcov.info | node_modules/.bin/codeclimate
